import type {
  Announcement,
  PeriodKey,
  Program,
  ProgramStatus,
  Review,
  ReviewCategory,
  ThemeKey,
} from "./types";

export const themeOptions: Array<{
  key: ThemeKey;
  label: string;
  description: string;
}> = [
  { key: "short", label: "짧은여행", description: "4박 이하" },
  { key: "month", label: "7일~한달살기", description: "체류형" },
  { key: "workation", label: "워케이션", description: "일과 여행" },
  { key: "local", label: "로컬프로젝트", description: "지역 미션" },
  { key: "returnFarm", label: "귀농귀촌", description: "농촌체험" },
  { key: "event", label: "공모/이벤트", description: "상금/공모" },
  { key: "pet", label: "반려견지원", description: "동반 여행" },
  { key: "half", label: "반값여행", description: "페이백" },
  { key: "daily", label: "일상지원금", description: "생활 혜택" },
  { key: "family", label: "아이랑", description: "가족 여행" },
  { key: "easy", label: "간편신청", description: "서류 최소" },
  { key: "benefit", label: "전용혜택", description: "회원 혜택" },
  { key: "exclusive", label: "전용이벤트", description: "한정 모집" },
];

export const periodOptions: Array<{ key: PeriodKey; label: string }> = [
  { key: "month", label: "한달살기(28일 이상)" },
  { key: "week", label: "일주일살기(5박~9박)" },
  { key: "twoWeeks", label: "2주살기(10박~17박)" },
  { key: "threeWeeks", label: "3주살기(18박~27박)" },
  { key: "under4", label: "짧은여행(4박 이하)" },
];

export const regions = [
  "전체",
  "해외",
  "전국",
  "서울",
  "부산",
  "대구",
  "인천",
  "광주",
  "대전",
  "울산",
  "세종",
  "경기",
  "강원",
  "충북",
  "충남",
  "전북",
  "전남",
  "경북",
  "경남",
  "제주",
];

const image = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

export const programs: Program[] = [
  {
    id: 1001,
    title: "강릉 파도 워케이션 6월 참가자 모집",
    slug: "gangneung-wave-workation",
    region: "강원",
    city: "강릉시",
    summary:
      "해변 공유오피스와 지역 체험을 결합한 5박 6일 리모트워크 프로그램입니다.",
    description:
      "강릉 바다 근처 업무공간, 로컬 네트워킹, 커피 로스터리 투어를 묶어 일과 회복을 함께 설계한 워케이션입니다.",
    theme: "workation",
    categories: ["workation", "benefit", "easy"],
    hashtags: ["워케이션", "강원", "공유오피스"],
    periodKey: "week",
    activityStart: "2026-06-10",
    activityEnd: "2026-06-15",
    recruitStart: "2026-05-01",
    recruitEnd: "2026-05-28",
    target: "원격근무 가능 직장인 및 프리랜서",
    capacity: "24명",
    announcement: "2026-05-31 개별 안내",
    subsidyLabel: "숙박 3박 및 업무공간 무료",
    subsidyAmount: 420000,
    fee: "50,000원",
    applicants: 86,
    status: "open",
    sourceName: "강릉 로컬워크 운영사",
    sourceUrl: "https://example.com/notices/gangneung-workation",
    applyUrl: "https://example.com/apply/gangneung-workation",
    phone: "033-000-1201",
    image: image("photo-1507525428034-b723cf961d3e"),
    gallery: [
      image("photo-1507525428034-b723cf961d3e"),
      image("photo-1500530855697-b586d89ba3ee"),
      image("photo-1500534314209-a25ddb2bd429"),
    ],
    badges: ["숙박지원", "업무공간", "선착순", "SNS 미션"],
    body: [
      "참가자는 지정 숙소에 머무르며 오전에는 업무공간을 자유롭게 이용하고, 저녁에는 지역 파트너가 운영하는 체험에 참여합니다.",
      "노트북, 신분증, 재직 또는 활동 증빙을 준비해 주세요. 선정 후 불참 시 향후 동일 운영사 프로그램 참여가 제한될 수 있습니다.",
      "최종 모집 조건과 지원 범위는 운영기관 공고문을 기준으로 확인해야 합니다.",
    ],
  },
  {
    id: 1002,
    title: "남해 섬마을 한달살기 체험단",
    slug: "namhae-island-month",
    region: "경남",
    city: "남해군",
    summary:
      "바닷마을 숙소와 체험비를 지원받고 남해의 일상을 기록하는 장기체류 프로그램입니다.",
    description:
      "남해 읍내와 어촌마을을 오가며 살아보기, 로컬 장보기, 해안 산책 코스를 기록하는 29박 체류형 모집입니다.",
    theme: "month",
    categories: ["month", "local"],
    hashtags: ["한달살기", "섬", "장기체류"],
    periodKey: "month",
    activityStart: "2026-06-20",
    activityEnd: "2026-07-19",
    recruitStart: "2026-04-25",
    recruitEnd: "2026-05-20",
    target: "만 19세 이상 국내 거주자",
    capacity: "10팀",
    announcement: "2026-05-24 홈페이지 발표",
    subsidyLabel: "팀당 최대 1,400,000원",
    subsidyAmount: 1400000,
    fee: "자부담 20%",
    applicants: 172,
    status: "open",
    sourceName: "남해 체류관광 사무국",
    sourceUrl: "https://example.com/notices/namhae-month",
    applyUrl: "https://example.com/apply/namhae-month",
    phone: "055-000-4812",
    image: image("photo-1500534314209-a25ddb2bd429"),
    gallery: [
      image("photo-1500534314209-a25ddb2bd429"),
      image("photo-1519046904884-53103b34b206"),
      image("photo-1493558103817-58b2924bce98"),
    ],
    badges: ["숙박지원", "체험지원", "추첨제", "아이 동반 가능"],
    body: [
      "체류 기간 중 지역 상권 이용과 여행 기록 제출이 필수입니다.",
      "가족, 친구, 1인 여행 모두 신청할 수 있으며 팀 구성에 따라 지원금 한도가 달라질 수 있습니다.",
      "숙소 배정은 운영 사무국의 가용 객실 기준으로 안내됩니다.",
    ],
  },
  {
    id: 1003,
    title: "제천 반값여행 페이백 2차",
    slug: "jecheon-half-payback",
    region: "충북",
    city: "제천시",
    summary:
      "제천 여행경비의 일부를 지역상품권으로 돌려받는 반값여행형 지원 사업입니다.",
    description:
      "숙박, 식음, 체험 지출 증빙을 제출하면 기준 금액 내에서 지역상품권으로 환급받을 수 있습니다.",
    theme: "half",
    categories: ["half", "short", "easy"],
    hashtags: ["반값여행", "페이백", "충북"],
    periodKey: "under4",
    activityStart: "2026-06-01",
    activityEnd: "2026-06-30",
    recruitStart: "2026-05-07",
    recruitEnd: "2026-05-30",
    target: "만 18세 이상 여행자",
    capacity: "예산 소진 시까지",
    announcement: "접수순 검토",
    subsidyLabel: "1인 최대 100,000원 / 2인 이상 최대 200,000원",
    subsidyAmount: 200000,
    fee: "여행경비 선결제",
    applicants: 221,
    status: "upcoming",
    sourceName: "제천 관광지원센터",
    sourceUrl: "https://example.com/notices/jecheon-half",
    applyUrl: "https://example.com/apply/jecheon-half",
    phone: "043-000-3377",
    image: image("photo-1519681393784-d120267933ba"),
    gallery: [
      image("photo-1519681393784-d120267933ba"),
      image("photo-1501785888041-af3ef285b470"),
    ],
    badges: ["지역상품권", "선착순", "증빙필수", "모집예정"],
    body: [
      "여행 전 사전 신청이 필요하며 승인 전 발생한 지출은 환급 대상에서 제외될 수 있습니다.",
      "환급은 모바일 지역상품권으로 지급됩니다.",
      "숙박 영수증, 카드 영수증, 방문 인증 자료를 보관하세요.",
    ],
  },
  {
    id: 1004,
    title: "고흥 별빛 농촌살이 2주 프로젝트",
    slug: "goheung-starlight-farmstay",
    region: "전남",
    city: "고흥군",
    summary:
      "농촌 숙소, 천문 체험, 로컬 장터 미션을 결합한 13박 14일 프로젝트입니다.",
    description:
      "고흥의 농가와 별빛 명소를 경험하며 귀농귀촌 가능성을 탐색하는 체류형 프로그램입니다.",
    theme: "returnFarm",
    categories: ["returnFarm", "local", "month"],
    hashtags: ["귀농귀촌", "전남", "농촌체험"],
    periodKey: "twoWeeks",
    activityStart: "2026-06-12",
    activityEnd: "2026-06-25",
    recruitStart: "2026-04-30",
    recruitEnd: "2026-05-18",
    target: "농촌 생활에 관심 있는 개인 및 가족",
    capacity: "8팀",
    announcement: "2026-05-21 문자 안내",
    subsidyLabel: "숙박 및 체험비 80% 지원",
    subsidyAmount: 900000,
    fee: "자부담 150,000원 내외",
    applicants: 64,
    status: "open",
    sourceName: "고흥 귀농귀촌지원센터",
    sourceUrl: "https://example.com/notices/goheung-farmstay",
    applyUrl: "https://example.com/apply/goheung-farmstay",
    phone: "061-000-9920",
    image: image("photo-1464822759023-fed622ff2c3b"),
    gallery: [
      image("photo-1464822759023-fed622ff2c3b"),
      image("photo-1473773508845-188df298d2d1"),
    ],
    badges: ["가족 가능", "농촌체험", "추첨제", "장기체류"],
    body: [
      "참가자는 마을 운영자가 안내하는 공동 일정에 참여하고, 체류 후 간단한 후기를 제출합니다.",
      "농작업은 기상 상황에 따라 대체 프로그램으로 변경될 수 있습니다.",
    ],
  },
  {
    id: 1005,
    title: "부산 원도심 골목 스탬프투어",
    slug: "busan-alley-stamp-tour",
    region: "부산",
    city: "중구",
    summary:
      "원도심 카페, 서점, 전망 포인트를 연결한 당일형 스탬프투어 이벤트입니다.",
    description:
      "모바일 지도를 따라 지정 지점을 방문하면 굿즈와 지역 매장 할인권을 받을 수 있습니다.",
    theme: "short",
    categories: ["short", "daily", "event"],
    hashtags: ["짧은여행", "스탬프투어", "부산"],
    periodKey: "under4",
    activityStart: "2026-05-10",
    activityEnd: "2026-06-30",
    recruitStart: "2026-05-01",
    recruitEnd: "2026-06-20",
    target: "누구나",
    capacity: "1,000명",
    announcement: "현장 수령",
    subsidyLabel: "굿즈 및 제휴 할인권",
    subsidyAmount: 50000,
    fee: "무료",
    applicants: 39,
    status: "open",
    sourceName: "부산 원도심 관광협의체",
    sourceUrl: "https://example.com/notices/busan-stamp",
    applyUrl: "https://example.com/apply/busan-stamp",
    phone: "051-000-2230",
    image: image("photo-1534274988757-a28bf1a57c17"),
    gallery: [
      image("photo-1534274988757-a28bf1a57c17"),
      image("photo-1500530855697-b586d89ba3ee"),
    ],
    badges: ["당일", "무료", "선착순", "굿즈"],
    body: [
      "운영 기간 중 지정 장소를 방문해 스탬프를 모으면 안내소에서 리워드를 받을 수 있습니다.",
      "리워드는 재고 소진 시 조기 종료될 수 있습니다.",
    ],
  },
  {
    id: 1006,
    title: "전주 가족 주말여행 지원",
    slug: "jeonju-family-weekend",
    region: "전북",
    city: "전주시",
    summary:
      "아이 동반 가족을 위한 전통문화 체험비와 숙박 쿠폰을 지원합니다.",
    description:
      "한옥마을 외곽의 체험 공간을 연결해 가족이 조용하게 머물며 전주를 탐색할 수 있도록 설계했습니다.",
    theme: "family",
    categories: ["family", "short", "benefit"],
    hashtags: ["아이랑", "가족여행", "전주"],
    periodKey: "under4",
    activityStart: "2026-05-24",
    activityEnd: "2026-07-05",
    recruitStart: "2026-05-02",
    recruitEnd: "2026-05-22",
    target: "만 4세~12세 아동 동반 가족",
    capacity: "60팀",
    announcement: "2026-05-23 오전",
    subsidyLabel: "팀당 최대 180,000원",
    subsidyAmount: 180000,
    fee: "체험별 상이",
    applicants: 118,
    status: "open",
    sourceName: "전주 가족관광 사무국",
    sourceUrl: "https://example.com/notices/jeonju-family",
    applyUrl: "https://example.com/apply/jeonju-family",
    phone: "063-000-5011",
    image: image("photo-1500530855697-b586d89ba3ee"),
    gallery: [
      image("photo-1500530855697-b586d89ba3ee"),
      image("photo-1493809842364-78817add7ffb"),
    ],
    badges: ["아이 동반", "숙박쿠폰", "체험지원", "추첨제"],
    body: [
      "아동 동반 증빙이 필요하며 일부 체험은 사전 예약이 필요합니다.",
      "숙박 쿠폰은 제휴 숙소 예약 시에만 사용할 수 있습니다.",
    ],
  },
  {
    id: 1007,
    title: "제주 반려견 동반 로컬트립",
    slug: "jeju-pet-local-trip",
    region: "제주",
    city: "제주시",
    summary:
      "반려견 동반 숙소와 로컬 산책 코스를 묶은 3박 4일 체류 혜택입니다.",
    description:
      "펫 프렌들리 카페, 오름 산책, 반려견 촬영권을 포함한 제주 로컬 여행 지원 프로그램입니다.",
    theme: "pet",
    categories: ["pet", "short", "benefit"],
    hashtags: ["반려견", "제주", "펫트립"],
    periodKey: "under4",
    activityStart: "2026-06-01",
    activityEnd: "2026-06-25",
    recruitStart: "2026-05-10",
    recruitEnd: "2026-05-26",
    target: "반려견 등록을 완료한 보호자",
    capacity: "30팀",
    announcement: "2026-05-28",
    subsidyLabel: "숙소 할인 및 촬영권",
    subsidyAmount: 260000,
    fee: "자부담 30%",
    applicants: 47,
    status: "upcoming",
    sourceName: "제주 펫로컬 협의체",
    sourceUrl: "https://example.com/notices/jeju-pet",
    applyUrl: "https://example.com/apply/jeju-pet",
    phone: "064-000-1400",
    image: image("photo-1517423440428-a5a00ad493e8"),
    gallery: [
      image("photo-1517423440428-a5a00ad493e8"),
      image("photo-1500534314209-a25ddb2bd429"),
    ],
    badges: ["반려견 동반", "숙박할인", "촬영권", "사전신청"],
    body: [
      "맹견으로 분류되는 견종은 숙소 규정에 따라 참여가 제한될 수 있습니다.",
      "이동장, 목줄, 배변봉투 등 필수 준비물을 지참해야 합니다.",
    ],
  },
  {
    id: 1008,
    title: "군산 청년 로컬리서치 캠프",
    slug: "gunsan-youth-local-research",
    region: "전북",
    city: "군산시",
    summary:
      "청년 팀이 군산의 빈 공간과 로컬 브랜드를 조사하고 제안서를 만드는 프로젝트입니다.",
    description:
      "지역 관계자 인터뷰, 공간 답사, 결과 발표까지 이어지는 4박 5일 로컬 프로젝트입니다.",
    theme: "local",
    categories: ["local", "event", "benefit"],
    hashtags: ["로컬프로젝트", "청년", "군산"],
    periodKey: "week",
    activityStart: "2026-06-18",
    activityEnd: "2026-06-22",
    recruitStart: "2026-05-01",
    recruitEnd: "2026-05-25",
    target: "만 19세~39세 청년 개인 또는 팀",
    capacity: "15팀",
    announcement: "2026-05-29",
    subsidyLabel: "활동비 팀당 700,000원",
    subsidyAmount: 700000,
    fee: "무료",
    applicants: 91,
    status: "open",
    sourceName: "군산 로컬랩",
    sourceUrl: "https://example.com/notices/gunsan-local",
    applyUrl: "https://example.com/apply/gunsan-local",
    phone: "063-000-7788",
    image: image("photo-1497366811353-6870744d04b2"),
    gallery: [
      image("photo-1497366811353-6870744d04b2"),
      image("photo-1497366754035-f200968a6e72"),
    ],
    badges: ["활동비", "팀 신청", "결과발표", "서류심사"],
    body: [
      "참가팀은 캠프 마지막 날 지역 이해관계자 앞에서 리서치 결과를 발표합니다.",
      "선정팀에는 사전 온라인 오리엔테이션 일정이 별도로 안내됩니다.",
    ],
  },
  {
    id: 1009,
    title: "평창 숲속 리모트워크",
    slug: "pyeongchang-forest-remote",
    region: "강원",
    city: "평창군",
    summary:
      "숲 근처 숙소와 조용한 업무 라운지를 제공하는 집중형 워케이션입니다.",
    description:
      "짧은 회복과 깊은 집중이 필요한 팀과 1인 창작자를 위해 설계된 리모트워크 패키지입니다.",
    theme: "workation",
    categories: ["workation", "short", "benefit"],
    hashtags: ["숲", "집중", "리모트워크"],
    periodKey: "under4",
    activityStart: "2026-05-26",
    activityEnd: "2026-06-30",
    recruitStart: "2026-04-28",
    recruitEnd: "2026-05-16",
    target: "원격근무자, 창작자, 스타트업 팀",
    capacity: "50명",
    announcement: "상시 안내",
    subsidyLabel: "1인 최대 300,000원",
    subsidyAmount: 300000,
    fee: "숙박 타입별 상이",
    applicants: 134,
    status: "open",
    sourceName: "평창 포레스트워크",
    sourceUrl: "https://example.com/notices/pyeongchang-remote",
    applyUrl: "https://example.com/apply/pyeongchang-remote",
    phone: "033-000-6650",
    image: image("photo-1448375240586-882707db888b"),
    gallery: [
      image("photo-1448375240586-882707db888b"),
      image("photo-1501785888041-af3ef285b470"),
    ],
    badges: ["업무라운지", "숙박지원", "팀 가능", "선착순"],
    body: [
      "라운지 좌석은 예약제로 운영되며 화상회의룸은 1일 2시간까지 무료입니다.",
      "프로그램 참여 후 간단한 만족도 조사가 있습니다.",
    ],
  },
  {
    id: 1010,
    title: "울릉도 섬 체류 리워드",
    slug: "ulleung-island-reward",
    region: "경북",
    city: "울릉군",
    summary:
      "울릉도 5박 이상 체류 여행자를 대상으로 교통과 체험 리워드를 제공합니다.",
    description:
      "섬 체류 기간을 늘리고 지역 식당과 체험장을 이용한 여행자에게 리워드를 지급합니다.",
    theme: "month",
    categories: ["month", "benefit", "short"],
    hashtags: ["섬여행", "울릉도", "체류리워드"],
    periodKey: "week",
    activityStart: "2026-06-05",
    activityEnd: "2026-08-30",
    recruitStart: "2026-05-15",
    recruitEnd: "2026-06-05",
    target: "5박 이상 체류 예정 여행자",
    capacity: "120명",
    announcement: "접수 후 3일 이내",
    subsidyLabel: "1인 최대 250,000원",
    subsidyAmount: 250000,
    fee: "여행경비 선결제",
    applicants: 22,
    status: "upcoming",
    sourceName: "울릉 체류관광 안내소",
    sourceUrl: "https://example.com/notices/ulleung-reward",
    applyUrl: "https://example.com/apply/ulleung-reward",
    phone: "054-000-7100",
    image: image("photo-1500534314209-a25ddb2bd429"),
    gallery: [
      image("photo-1500534314209-a25ddb2bd429"),
      image("photo-1507525428034-b723cf961d3e"),
    ],
    badges: ["5박 이상", "교통리워드", "체험지원", "증빙필수"],
    body: [
      "선박 결항 등 천재지변으로 일정이 변경될 경우 운영 사무국에 즉시 알려야 합니다.",
      "리워드는 예산 상황에 따라 조기 마감될 수 있습니다.",
    ],
  },
  {
    id: 1011,
    title: "무주 귀농귀촌 미리살기",
    slug: "muju-rural-preview",
    region: "전북",
    city: "무주군",
    summary:
      "예비 귀촌인을 위한 마을 숙박, 농가 멘토링, 생활 인프라 탐방 프로그램입니다.",
    description:
      "무주의 마을과 생활권을 직접 경험하며 귀촌 가능성을 점검하는 3주 체류 프로그램입니다.",
    theme: "returnFarm",
    categories: ["returnFarm", "month"],
    hashtags: ["귀촌", "무주", "마을살이"],
    periodKey: "threeWeeks",
    activityStart: "2026-06-01",
    activityEnd: "2026-06-21",
    recruitStart: "2026-04-11",
    recruitEnd: "2026-05-08",
    target: "귀촌 희망자",
    capacity: "6팀",
    announcement: "2026-05-12",
    subsidyLabel: "숙박 전액 및 멘토링 지원",
    subsidyAmount: 1100000,
    fee: "식비 자부담",
    applicants: 203,
    status: "closed",
    sourceName: "무주 귀농귀촌센터",
    sourceUrl: "https://example.com/notices/muju-rural",
    applyUrl: "https://example.com/apply/muju-rural",
    phone: "063-000-9090",
    image: image("photo-1473773508845-188df298d2d1"),
    gallery: [
      image("photo-1473773508845-188df298d2d1"),
      image("photo-1464822759023-fed622ff2c3b"),
    ],
    badges: ["모집종료", "숙박전액", "멘토링", "장기체류"],
    body: [
      "현재 모집은 종료되었습니다. 다음 회차 오픈 알림을 신청할 수 있습니다.",
      "프로그램 종료 후 귀촌 상담을 희망하면 별도 상담 일정이 제공됩니다.",
    ],
  },
  {
    id: 1012,
    title: "목포 미식여행 서포터즈",
    slug: "mokpo-foodie-supporters",
    region: "전남",
    city: "목포시",
    summary:
      "목포의 식당과 시장을 방문하고 콘텐츠를 제작하는 미식 여행 서포터즈입니다.",
    description:
      "여행자 시선으로 목포 미식 코스를 발굴하고 카드뉴스 또는 숏폼 콘텐츠를 제출합니다.",
    theme: "event",
    categories: ["event", "short", "local"],
    hashtags: ["미식여행", "서포터즈", "목포"],
    periodKey: "under4",
    activityStart: "2026-05-20",
    activityEnd: "2026-06-15",
    recruitStart: "2026-04-20",
    recruitEnd: "2026-05-02",
    target: "SNS 공개 계정 운영자",
    capacity: "40명",
    announcement: "2026-05-04",
    subsidyLabel: "활동비 150,000원",
    subsidyAmount: 150000,
    fee: "무료",
    applicants: 312,
    status: "earlyClosed",
    sourceName: "목포 미식관광 운영국",
    sourceUrl: "https://example.com/notices/mokpo-food",
    applyUrl: "https://example.com/apply/mokpo-food",
    phone: "061-000-7001",
    image: image("photo-1504674900247-0877df9cc836"),
    gallery: [
      image("photo-1504674900247-0877df9cc836"),
      image("photo-1517248135467-4c7edcad34c4"),
    ],
    badges: ["조기종료", "활동비", "SNS 필요", "콘텐츠 제출"],
    body: [
      "예상보다 많은 신청으로 모집이 조기 종료되었습니다.",
      "선정자는 개별 연락을 통해 방문 미션과 콘텐츠 제출 기준을 안내받습니다.",
    ],
  },
];

export const reviewCategories: Array<{ key: "all" | ReviewCategory; label: string }> = [
  { key: "all", label: "전체" },
  { key: "programTip", label: "프로그램 후기/팁" },
  { key: "selected", label: "선정됐어요" },
  { key: "rejected", label: "탈락했어요" },
  { key: "trip", label: "여행후기" },
  { key: "free", label: "자유수다" },
  { key: "question", label: "질문답변" },
];

export const reviews: Review[] = [
  {
    id: 501,
    title: "워케이션은 숙소 위치보다 업무공간 콘센트가 중요했어요",
    category: "programTip",
    programId: 1001,
    author: "노트북여행자",
    date: "2026-05-03T20:12:00",
    excerpt:
      "바다가 보이는 숙소도 좋지만 실제 만족도는 업무공간, 의자, 주변 식당 동선에서 갈렸습니다.",
    body:
      "첫 워케이션을 준비하면서 숙소 사진만 봤는데, 막상 지내보니 의자 높이와 콘센트 위치가 훨씬 중요했습니다. 신청 전에 업무공간 사진과 운영 시간을 꼭 확인해 보세요.",
    images: [image("photo-1497366811353-6870744d04b2")],
    likes: 18,
    comments: 4,
    badge: "찐후기",
  },
  {
    id: 502,
    title: "남해 한달살기 서류 통과했어요",
    category: "selected",
    programId: 1002,
    author: "섬으로출근",
    date: "2026-05-02T09:30:00",
    excerpt:
      "지원동기에 지역에서 하고 싶은 일을 구체적으로 적은 게 도움이 된 것 같습니다.",
    body:
      "단순히 쉬고 싶다는 내용보다 지역 가게, 산책 코스, 기록 계획을 적었습니다. 선정 문자를 받고 보니 준비 시간이 아깝지 않았어요.",
    images: [image("photo-1519046904884-53103b34b206")],
    likes: 32,
    comments: 11,
  },
  {
    id: 503,
    title: "페이백 프로그램은 영수증 폴더를 따로 만들면 편해요",
    category: "programTip",
    programId: 1003,
    author: "영수증수집가",
    date: "2026-04-30T18:44:00",
    excerpt:
      "반값여행은 신청보다 정산이 더 중요했습니다. 사진첩 앨범을 만들어두면 제출할 때 덜 헤맵니다.",
    body:
      "카드 영수증과 방문 인증 사진을 하루 단위로 저장해두니 정산 서류 만들 때 편했습니다. 숙박, 식당, 체험을 구분해두는 것도 추천합니다.",
    images: [],
    likes: 21,
    comments: 6,
  },
  {
    id: 504,
    title: "목포 서포터즈는 떨어졌지만 다음엔 더 일찍 준비하려고요",
    category: "rejected",
    programId: 1012,
    author: "미식기록장",
    date: "2026-04-29T21:10:00",
    excerpt:
      "조기마감이라 아쉽지만 포트폴리오 링크를 미리 정리해야겠다는 교훈을 얻었습니다.",
    body:
      "이번에는 신청서를 급하게 냈습니다. 다음에는 SNS 링크, 이전 콘텐츠, 방문 가능한 날짜를 미리 정리해두려고 합니다.",
    images: [image("photo-1504674900247-0877df9cc836")],
    likes: 12,
    comments: 2,
  },
  {
    id: 505,
    title: "부산 원도심 당일 코스, 아이랑도 충분했어요",
    category: "trip",
    programId: 1005,
    author: "주말기차",
    date: "2026-04-28T16:25:00",
    excerpt:
      "스탬프 지점 사이가 생각보다 가까워서 오전 늦게 시작해도 여유 있었습니다.",
    body:
      "카페와 전망 포인트 사이 동선이 좋아서 아이와 걷기에도 무리가 없었습니다. 다만 굿즈 수령처 마감 시간은 꼭 확인하세요.",
    images: [image("photo-1534274988757-a28bf1a57c17")],
    likes: 27,
    comments: 5,
  },
  {
    id: 506,
    title: "귀농귀촌 프로그램은 가족 일정 합의가 먼저네요",
    category: "free",
    programId: 1004,
    author: "느린달력",
    date: "2026-04-25T11:12:00",
    excerpt:
      "2주 이상 체류는 혼자만의 결심으로는 어렵더라고요. 생활 리듬을 먼저 맞춰보는 중입니다.",
    body:
      "아이 학교, 반려동물, 재택근무 일정까지 같이 봐야 해서 신청 전에 가족 회의를 했습니다. 그래도 기대됩니다.",
    images: [],
    likes: 9,
    comments: 8,
  },
];

export const announcements: Announcement[] = [
  {
    id: 701,
    title: "목포 미식여행 서포터즈 모집이 조기 종료되었습니다.",
    type: "close",
    date: "2026-05-04T09:20:00",
    programId: 1012,
    body:
      "운영기관 공지 기준으로 신청 접수가 마감되었습니다. 이미 접수한 신청자는 선정 발표 일정을 확인해 주세요.",
  },
  {
    id: 702,
    title: "제천 반값여행 2차 접수 시작 예정일이 5월 7일로 확정되었습니다.",
    type: "open",
    date: "2026-05-03T18:10:00",
    programId: 1003,
    body:
      "사전 신청 후 승인된 여행 경비만 환급 대상이 될 수 있으니 여행 전 접수 여부를 먼저 확인하세요.",
  },
  {
    id: 703,
    title: "전주 가족 주말여행 일부 체험장이 주말 예약제로 변경되었습니다.",
    type: "change",
    date: "2026-05-02T14:44:00",
    programId: 1006,
    body:
      "체험장별 운영 시간이 다르므로 신청 전 세부 일정표를 다시 확인하는 것을 권장합니다.",
  },
  {
    id: 704,
    title: "후기 게시판 클린 운영 기준 안내",
    type: "notice",
    date: "2026-05-01T12:00:00",
    body:
      "개인정보, 허위 선정 인증, 외부 광고성 게시물은 숨김 처리될 수 있습니다. 경험 공유는 언제나 환영합니다.",
  },
  {
    id: 705,
    title: "강릉 파도 워케이션 모집 인원이 24명으로 조정되었습니다.",
    type: "change",
    date: "2026-04-30T17:30:00",
    programId: 1001,
    body:
      "숙소 확보 상황에 따라 모집 인원이 기존 안내보다 줄었습니다. 기존 신청자는 정상 접수 상태를 유지합니다.",
  },
];

export const statusLabels: Record<ProgramStatus, string> = {
  open: "모집중",
  upcoming: "모집예정",
  closed: "모집종료",
  earlyClosed: "조기종료",
};

export function getProgramById(id: number): Program | undefined {
  return programs.find((program) => program.id === id);
}

export function getReviewById(id: number): Review | undefined {
  return reviews.find((review) => review.id === id);
}

export function getAnnouncementById(id: number): Announcement | undefined {
  return announcements.find((announcement) => announcement.id === id);
}
