import "server-only";

import { isDemoModeEnabled } from "@/lib/demo-mode";
import type { HostApplication } from "@/lib/host-operations";

export const seedHostApplications: HostApplication[] = [
  {
    id: "app-001",
    programTitle: "강릉 파도 워케이션 6월",
    applicantName: "김서연",
    email: "seoyeon@example.com",
    phone: "010-4421-9031",
    status: "accepted",
    submittedAt: "2026-05-03T09:20:00+09:00",
    paymentAmount: 50000,
    receiptCount: 3,
    signatureCompleted: true,
    reviewSubmitted: false,
    memo: "원격근무 가능 여부 확인 완료",
  },
  {
    id: "app-002",
    programTitle: "강릉 파도 워케이션 6월",
    applicantName: "박민준",
    email: "minjun@example.com",
    phone: "010-1384-7220",
    status: "screening",
    submittedAt: "2026-05-03T13:05:00+09:00",
    paymentAmount: 0,
    receiptCount: 0,
    signatureCompleted: false,
    reviewSubmitted: false,
    memo: "자기소개 답변 보강 필요",
  },
  {
    id: "app-003",
    programTitle: "남해 섬마을 한달살기",
    applicantName: "이하늘",
    email: "haneul@example.com",
    phone: "010-7742-1188",
    status: "checkedIn",
    submittedAt: "2026-05-02T17:42:00+09:00",
    paymentAmount: 280000,
    receiptCount: 8,
    signatureCompleted: true,
    reviewSubmitted: false,
    memo: "숙소 배정 완료, 1차 영수증 수집 중",
  },
  {
    id: "app-004",
    programTitle: "제천 반값여행 네이버 2차",
    applicantName: "정유진",
    email: "yujin@example.com",
    phone: "010-2190-5366",
    status: "completed",
    submittedAt: "2026-05-01T11:12:00+09:00",
    paymentAmount: 120000,
    receiptCount: 5,
    signatureCompleted: true,
    reviewSubmitted: true,
    memo: "환급 서류와 증빙 모두 완료",
  },
  {
    id: "app-005",
    programTitle: "고흥 별빛 귀촌 2주 프로그램",
    applicantName: "최도윤",
    email: "doyun@example.com",
    phone: "010-8841-6120",
    status: "submitted",
    submittedAt: "2026-05-04T08:10:00+09:00",
    paymentAmount: 0,
    receiptCount: 0,
    signatureCompleted: false,
    reviewSubmitted: false,
    memo: "가족 동반 여부 확인 필요",
  },
  {
    id: "app-006",
    programTitle: "로컬살롱",
    applicantName: "오지후",
    email: "jihyu@example.com",
    phone: "010-5520-8821",
    status: "accepted",
    submittedAt: "2026-05-05T15:32:00+09:00",
    paymentAmount: 50000,
    receiptCount: 0,
    signatureCompleted: false,
    reviewSubmitted: false,
    memo: "입금 확인 완료, 숙소 위치 안내 전송 필요",
  },
  {
    id: "app-007",
    programTitle: "나를 담는 차 실험실",
    applicantName: "한소민",
    email: "somin@example.com",
    phone: "010-7341-2901",
    status: "screening",
    submittedAt: "2026-05-05T18:47:00+09:00",
    paymentAmount: 0,
    receiptCount: 0,
    signatureCompleted: false,
    reviewSubmitted: false,
    memo: "블렌딩 상품 기획 동기 확인 필요",
  },
];

export function readHostApplicationsFromStorage(): HostApplication[] {
  return isDemoModeEnabled() ? seedHostApplications : [];
}
