export const nuvioIcons = {
  arrowCircleRight: "/icons/nuvio/arrow-circle-right.svg",
  bell: "/icons/nuvio/bell.svg",
  bookmark: "/icons/nuvio/bookmark.svg",
  bookmarkFilled: "/icons/nuvio/bookmark-filled.svg",
  calendar: "/icons/nuvio/calendar.svg",
  coupon: "/icons/nuvio/coupon.svg",
  dropdown: "/icons/nuvio/dropdown.svg",
  dropup: "/icons/nuvio/dropup.svg",
  formEditorBack: "/icons/nuvio/form-editor-back.svg",
  formItemCondition: "/icons/nuvio/form-item-condition.svg",
  formItemCopy: "/icons/nuvio/form-item-copy.svg",
  formItemTrash: "/icons/nuvio/form-item-trash.svg",
  formRequiredToggleOff: "/icons/nuvio/form-required-toggle-off.svg",
  formRequiredToggleOn: "/icons/nuvio/form-required-toggle-on.svg",
  formSelectDropdown: "/icons/nuvio/form-select-dropdown.svg",
  headerActionFrame: "/icons/nuvio/header-action-frame.svg",
  login: "/icons/nuvio/login.svg",
  mail: "/icons/nuvio/mail.svg",
  map: "/icons/nuvio/map.svg",
  menuReorder: "/icons/nuvio/menu-reorder.svg",
  message: "/icons/nuvio/message.svg",
  moreHorizontal: "/icons/nuvio/more-horizontal.svg",
  notificationDot: "/icons/nuvio/notification-dot.svg",
  phone: "/icons/nuvio/phone.svg",
  place: "/icons/nuvio/place.svg",
  promotion: "/icons/nuvio/promotion.svg",
  quantityDisabled: "/icons/nuvio/quantity-disabled.svg",
  quantityMinus: "/icons/nuvio/quantity-minus.svg",
  quantityPlus: "/icons/nuvio/quantity-plus.svg",
  quantityPlusDisabled: "/icons/nuvio/quantity-plus-disabled.svg",
  review: "/icons/nuvio/review.svg",
  settings: "/icons/nuvio/settings.svg",
  share: "/icons/nuvio/share.svg",
  user: "/icons/nuvio/user.svg",
} as const;

export type NuvioIconName = keyof typeof nuvioIcons;
