revoke all privileges on function
  public.activate_review_visibility_hold(uuid, text, uuid, text, jsonb),
  public.current_user_can_review_application(uuid),
  public.normalize_review_host_reply_write(),
  public.normalize_review_report_lifecycle(),
  public.normalize_review_request_write(),
  public.normalize_review_write(),
  public.prevent_expired_active_review_request(),
  public.prevent_invalid_review_helpful_vote(),
  public.prevent_invalid_review_host_reply_review(),
  public.prevent_invalid_review_report(),
  public.prevent_review_content_version_mutation(),
  public.prevent_review_hard_delete(),
  public.prevent_review_helpful_vote_event_mutation(),
  public.prevent_review_host_reply_event_mutation(),
  public.prevent_review_moderation_check_mutation(),
  public.prevent_review_publish_with_active_hold(),
  public.prevent_review_report_event_mutation(),
  public.prevent_review_report_origin_mutation(),
  public.prevent_review_request_event_mutation(),
  public.prevent_review_status_event_mutation(),
  public.prevent_review_system_field_mutation(),
  public.prevent_review_visibility_hold_event_mutation(),
  public.prevent_review_visibility_hold_mutation(),
  public.prevent_unauthorized_review_deleted_status(),
  public.recalculate_review_helpful_count(uuid),
  public.recalculate_review_host_reply_count(uuid),
  public.record_review_content_version_from_review(),
  public.record_review_helpful_vote_event_from_vote(),
  public.record_review_host_reply_event_from_reply(),
  public.record_review_report_event_from_report(),
  public.record_review_request_event_from_request(),
  public.record_review_status_event_from_review(),
  public.record_review_visibility_hold_event_from_hold(),
  public.refresh_application_review_submitted(uuid),
  public.release_review_visibility_hold(uuid, text, uuid, text),
  public.review_host_reply_event_action(text, text, boolean, boolean),
  public.review_image_url_is_safe(text),
  public.review_images_are_safe(jsonb),
  public.review_is_publicly_visible(uuid),
  public.review_report_event_action(text, text, boolean),
  public.review_report_visibility_hold_reason(text),
  public.review_request_event_action(text, text),
  public.review_status_event_action(public.review_status, public.review_status),
  public.review_visibility_hold_event_action(text, text, boolean, boolean),
  public.sync_application_review_submitted(),
  public.sync_review_helpful_count_from_vote(),
  public.sync_review_host_reply_count_from_reply(),
  public.sync_review_moderation_check(),
  public.sync_review_request_from_review(),
  public.sync_review_visibility_hold_from_moderation(),
  public.sync_review_visibility_hold_from_report(),
  public.validate_review_request_completion()
from anon, authenticated, public;
